### ISSUE TITLE
$MY_SECRET will be printed

### ISSUE THREAD

**Issue by yzgyyang** [onejar99/gitbook-build-publish-action#1]
I am just wondering if this is a security hazard to print $MY_SECRET - which could be a user's access GH token.

https://github.com/onejar99/gitbook-build-publish-action/blob/master/entrypoint.sh#L20

**Comment by onejar99** [comment]
$MY_SECRET will be masked by GitHub Action when printing, so the access token won't be disclosed. But it's unnecessary to print it. I have removed it. Thank you for reminding!
